name: save release notes

on: [workflow_call,workflow_dispatch]
jobs:
  save-release-notes-to-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'release-notes'
      - name: save
        run: |
            latest_release=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest |yq '.name')
            curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest |yq '.body' > ${latest_release}.md

      - name: web-site
        run: |
            sudo apt-get install ruby-full build-essential zlib1g-dev
            gem install jekyll bundler
            jekyll new myblog
            mv myblog/* ./

      # - uses:  helaili/jekyll-action@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pushes charts to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: 'prow'
          user-email: prow-obot@prow-io
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: release-notes
