# name: main
#
# on:
#   push:
#     branches:
#       - main
# env:
#   TEST: "ubuntu-latest"
#
# permissions:
#   packages: write
#   contents: read
#
# jobs:
#   build1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Generate Changelog
#         run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
#       - name: Release
#         if: startsWith(github.ref, 'refs/tags/')
#         uses: softprops/action-gh-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           generate_release_notes: true
#           files: |
#             ${{ github.workspace }}-CHANGELOG.txt
#   output-variable: # 让build4传递环境变量必要的操作！！！
#     runs-on: ubuntu-latest
#     outputs:
#       test: ${{ steps.output_variables.outputs.test }}
#       # aaa: ${{ steps.output_variables.outputs.aaa }}
#       # tessst: ${{ steps.output_variables.outputs.tessst }}
#
# name: Main
#
# on: push
# # permissions:
# #   contents: write
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Build
#         run: echo ${{ github.sha }} > Release.txt
#       - name: Test
#         run: cat Release.txt
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
#           files: Release.txt
#           generate_release_notes: true
# name: Main
#
# on:
#   push:
#     tags:
#       - "v*.*.*"
#
# jobs:
#   auto-generate-release-notes:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           generate_release_notes: true
#
  # save-release-notes-to-file:
    # needs: auto-generate-release-notes
    # uses: ./.github/workflows/call-save-release-notes.yaml
    # secrets: inherit
    # steps:
    #   - uses: actions/checkout@v3
    #     with:
    #       fetch-depth: 0
    #
    #   - name: set environment variable
    #     run: |
    #       AAAAAAA="我是A"
    #       export BBBBBBB="我是B"
    #       echo "CCCCCCC=${AAAAAAA,,}" >> ${GITHUB_ENV} # 由于每个job的文件系统都是独立的，本job产生的env没法被其他job使用
#       - name: output environment variable
#         id: output_variables
#         run: |
#           echo $AAAAAAA
#           echo $BBBBBBB
#           echo ${{ env.CCCCCCC }}

#           # export REGISTRY=ghcr.io
#           # export REPO=kubean-io
#           # export IMAGE_TAG=latest
#           # export SPRAY_IMAGE_TAG_SHORT_SHA=latest
#           # make security-scanning
#           #
#           # wget https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.tar.gz
#           # tar xf trivy_0.29.0_Linux-64bit.tar.gz
#           # mv trivy /usr/local/bin/trivy
#           # trivy -v
#           # echo "AAA=我是变量内容" >> ${GITHUB_ENV}
#           # echo "===============输出变量内容：${{ env.AAA }}"
#           # echo ::set-output name=aaa::${AAA}
#           # echo ::set-output name=test::${{ env.TEST }}

#           # echo ::set-output name=tessst::${{ env.TESSST }}
#           # AAA="我是变量"


#           echo "test=${AAA}" >> $GITHUB_OUTPUT


      # kube_version:
      #   required: true
      #   type: string
      #   default: "kubean-io"
      # calico_version:
      #   required: true
      #   type: string
      #   default: "linux/amd64,linux/arm64"
      # cni_version:
      #   required: true
      #   type: string
      #   default: "ghcr.io"
      # containerd_version:
      #   required: true
      #   type: string
      #   default: "linux/amd64,linux/arm64"
      # cilium_version:
      #   required: true
      #   type: string
      #   default: "ghcr.io"
      # etcd_version:
      #   required: true
      #   type: string
      #   default: "linux/amd64,linux/arm64"
# permissions:
#   contents: write
name: incremental-packages

on:
  workflow_dispatch:
    inputs:
      file_suffix:
        required: true
        type: string
        default: "add_etcd_version"
      image_arch:
        required: true
        type: string
        default: "amd64 arm64"
      kube_version:
        required: false
        type: string
      calico_version:
        required: false
        type: string
      cni_version:
        required: false
        type: string
      containerd_version:
        required: false
        type: string
      cilium_version:
        required: false
        type: string
      etcd_version:
        required: false
        type: string
jobs:
  incremental-packages:
    # needs: output-variable
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate incremental offline packages
        run: |
          export IMAGE_ARCH="${{ inputs.image_arch }}"
          export KUBE_VERSION="${{ inputs.kube_version }}"
          export CALICO_VERSION="${{ inputs.calico_version }}"
          export CNI_VERSION="${{ inputs.cni_version }}"
          export CONTAINERD_VERSION="${{ inputs.containerd_version }}"
          export CILIUM_VERSION="${{ inputs.cilium_version }}"
          export ETCD_VERSION="${{ inputs.etcd_version }}"
          export FILE_SUFFIX="${{ inputs.file_suffix }}"
          export OFFLINE_NGINX_IP="${{ secrets.OFFLINE_NGINX_IP }}"
          export OFFLINE_NGINX_PASSWORD="${{ secrets.OFFLINE_NGINX_PASSWORD }}"
          bash hack/incremental-pkgs.sh
#   build2:
#     needs: [build1,output-variable]
#     uses: ./.github/workflows/call-test1.yaml
#     secrets: inherit
#     with:
#       TEST1: ${{ needs.output-variable.outputs.test }} # 传递环境到同目录其他CI文件
#       AAA: ${{ needs.output-variable.outputs.aaa }}
