name: incremental-packages

on:
  workflow_dispatch:
    inputs:
      image_arch:
        type: choice
        options:
        - "amd64 arm64"
        - "amd64"
        - "arm64"
        required: true
jobs:
  incremental-packages:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate incremental offline packages
        run: |
          echo 123
